### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-2-evaluacion-intermedia-lauramorenochico#1]
Really cool job @lauramorenochico  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Fix the if's conditionals. Check if the first condition is correct, check if the number is less than 1 or greater than 100: https://github.com/Adalab/modulo-2-evaluacion-intermedia-lauramorenochico/blob/e39f5e264e18673e48f0f2749937769ebcf696f7/js/main.js#L21 
- [x] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number: https://github.com/Adalab/modulo-2-evaluacion-intermedia-lauramorenochico/blob/e39f5e264e18673e48f0f2749937769ebcf696f7/js/main.js#L20 
- [x] Remove debugger and other unnecessary code: https://github.com/Adalab/modulo-2-evaluacion-intermedia-lauramorenochico/blob/e39f5e264e18673e48f0f2749937769ebcf696f7/js/main.js#L3

### JavaScript: advanced

- [x] Check if the `<input>` has an empty value or text.
- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### JavaScript: good practices

- [x] Move variables and constants declarations to the top of the file.

### HTML

- [x] Use a `label` to define the content of the input.
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input.
- [x] Use placeholder attribute instead of value one to show a field's hint.

### CSS

- [x] Avoid adding styles until the js code is solid as a rock.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by lauramorenochico** [comment]
checked and reviewed all issues

**Comment by ytaylordev** [comment]
Good job :)
